name: Deploy Lambda Function With Tags

on:
  push:
    paths:
      - "src/**"
    branches: [ dev, staging ]
    tags:
      - v1.*
  pull_request:
    branches: [ dev, staging ]

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name ${{ secrets.AWS_ARN_LAMBDA }} \
          --zip-file=fileb://src/code.zip