name: Deploy Lambda Function With Tags

on:
  push:
    paths:
      - "src/**"
    branches: [ prod ]
    tags:
      - v1.*
  pull_request:
    branches: [ prod ]

jobs:
  prod:
    name: Enviroment Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Release
        id: prod
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name ${{ secrets.AWS_ARN_LAMBDA }} \
          --zip-file=fileb://src/code.zip