name: Deploy Lambda Function With Tags

on:
  push:
    paths:
      - "src/**"
    branches: [ prod, dev, staging ]
    tags:
      - 1.*
  pull_request:
    branches: [ prod, dev, staging ]

jobs:

  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name arn:aws:lambda:us-east-1:454362774081:function:SIMPLE_LAMBDA_CICD \
          --zip-file=fileb://src/code.zip
  
  staging:
    runs-on: ubuntu-latest
    needs: 
      - dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name arn:aws:lambda:us-east-1:454362774081:function:SIMPLE_LAMBDA_CICD \
          --zip-file=fileb://src/code.zip
  
  prod:
    runs-on: ubuntu-latest
    needs: 
      - dev
      - staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name arn:aws:lambda:us-east-1:454362774081:function:SIMPLE_LAMBDA_CICD \
          --zip-file=fileb://src/code.zip